using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DbUp.Generators
{
    [Generator]
    public class DbUpScriptGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor NoParameterlessConstructor = new(
            id: "DBUP001",
            title: "IScript implementation must have a parameterless constructor",
            messageFormat: "'{0}' implements IScript but has no parameterless constructor; it cannot be used with WithGeneratedScripts()",
            category: "DbUp",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true
        );

        private static readonly DiagnosticDescriptor NoScriptsFound = new(
            id: "DBUP002",
            title: "No IScript implementations found",
            messageFormat: "[assembly: DbUpGenerateScripts] is applied but no non-abstract IScript implementations were found",
            category: "DbUp",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true
        );

        private const string PostInitSource =
            @"// <auto-generated />
namespace DbUp
{
    /// <summary>
    /// Apply this attribute at the assembly level to opt in to DbUp source-generated script registration.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
    public sealed class DbUpGenerateScriptsAttribute : System.Attribute { }

    /// <summary>
    /// Script execution type for source-generated scripts. Values mirror DbUp.Support.ScriptType.
    /// </summary>
    public enum DbUpScriptType
    {
        /// <summary>Script runs only once and is recorded in the journal.</summary>
        RunOnce = 0,
        /// <summary>Script runs every time regardless of journal state.</summary>
        RunAlways = 1
    }

    /// <summary>
    /// Apply to an IScript class to configure script options for source-generated registration.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false)]
    public sealed class DbUpScriptAttribute : System.Attribute
    {
        /// <summary>The script execution type. Defaults to RunOnce.</summary>
        public DbUpScriptType ScriptType { get; set; } = DbUpScriptType.RunOnce;

        /// <summary>The run group order. Defaults to 100.</summary>
        public int RunGroupOrder { get; set; } = 100;
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "DbUpAttributes.g.cs",
                    SourceText.From(PostInitSource, Encoding.UTF8)
                );
            });

            // Check for [assembly: DbUpGenerateScripts]
            var hasMarker = context
                .SyntaxProvider.ForAttributeWithMetadataName(
                    "DbUp.DbUpGenerateScriptsAttribute",
                    predicate: static (node, _) => true,
                    transform: static (ctx, _) => true
                )
                .Collect()
                .Select(static (items, _) => items.Any());

            // Find all non-abstract IScript implementations
            var scriptClasses = context
                .SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetScriptInfo(ctx)
                )
                .Where(static m => m is not null)!;

            // Get and sanitize the assembly name for use as a namespace
            var assemblyNamespace = context.CompilationProvider.Select(
                static (c, _) => SanitizeNamespace(c.AssemblyName ?? "DbUp.Generated")
            );

            var combined = scriptClasses
                .Collect()
                .Select(static (items, _) => items.Distinct().ToImmutableArray())
                .Combine(hasMarker)
                .Combine(assemblyNamespace);

            context.RegisterSourceOutput(
                combined,
                static (spc, input) =>
                {
                    var classes = input.Left.Left;
                    var markerPresent = input.Left.Right;
                    var targetNamespace = input.Right; // This is our sanitized assembly name

                    if (!markerPresent)
                        return;

                    // Report diagnostics for classes without parameterless constructors
                    var validClasses = ImmutableArray.CreateBuilder<ScriptInfo>();
                    foreach (var info in classes)
                    {
                        if (info is null)
                            continue;
                        if (!info.HasParameterlessConstructor)
                        {
                            var linePosition = new LinePosition(info.StartLine, info.StartChar);
                            var lineSpan = new LinePositionSpan(linePosition, linePosition);

                            var location = Location.Create(
                                info.FilePath,
                                new Microsoft.CodeAnalysis.Text.TextSpan(),
                                lineSpan
                            );

                            spc.ReportDiagnostic(
                                Diagnostic.Create(
                                    NoParameterlessConstructor,
                                    location,
                                    info.FullyQualifiedName
                                )
                            );
                            continue;
                        }
                        validClasses.Add(info);
                    }

                    if (validClasses.Count == 0)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(NoScriptsFound, Location.None));
                        return;
                    }
                    validClasses.Sort(
                        (a, b) =>
                        {
                            int result = a.RunGroupOrder.CompareTo(b.RunGroupOrder);
                            if (result != 0)
                                return result;

                            return string.Compare(
                                a.FullyQualifiedName,
                                b.FullyQualifiedName,
                                StringComparison.Ordinal
                            );
                        }
                    );

                    var sb = new StringBuilder();
                    sb.AppendLine(
                        $$"""
// <auto-generated />
using DbUp.Builder;
using DbUp.Engine;
using DbUp.Support;

namespace {{targetNamespace}}
{
    /// <summary>
    /// Source-generated DbUp script registrations.
    /// </summary>
    public static class DbUpGeneratedScripts
    {
        /// <summary>
        /// Registers all source-generated IScript implementations with the builder.
        /// </summary>
        public static UpgradeEngineBuilder WithGeneratedScripts(this UpgradeEngineBuilder builder)
        {
"""
                    );

                    foreach (var info in validClasses)
                    {
                        if (info.HasNonDefaultOptions)
                        {
                            sb.AppendLine(
                                $"            builder.WithScript(\"{info.FullyQualifiedName}\", new {info.FullyQualifiedName}(), new SqlScriptOptions {{ ScriptType = ScriptType.{info.ScriptTypeName}, RunGroupOrder = {info.RunGroupOrder} }});"
                            );
                        }
                        else
                        {
                            sb.AppendLine(
                                $"            builder.WithScript(\"{info.FullyQualifiedName}\", new {info.FullyQualifiedName}());"
                            );
                        }
                    }
                    sb.AppendLine(
                        """
            return builder;
        }
    }
}
"""
                    );
                    spc.AddSource(
                        "DbUpGeneratedScripts.g.cs",
                        SourceText.From(sb.ToString(), Encoding.UTF8)
                    );
                }
            );
        }

        private static ScriptInfo? GetScriptInfo(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol =
                context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol is null || symbol.IsAbstract)
                return null;

            if (!symbol.AllInterfaces.Any(i => i.ToDisplayString() == "DbUp.Engine.IScript"))
                return null;

            var hasParameterlessCtor = symbol.InstanceConstructors.Any(c =>
                c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public
            );

            // Read [DbUpScript] attribute if present
            var scriptTypeName = "RunOnce";
            var runGroupOrder = 100;
            var hasNonDefaultOptions = false;

            var attr = symbol
                .GetAttributes()
                .FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "DbUp.DbUpScriptAttribute"
                );

            if (attr is not null)
            {
                foreach (var namedArg in attr.NamedArguments)
                {
                    if (namedArg.Key == "ScriptType" && namedArg.Value.Value is int scriptTypeVal)
                    {
                        scriptTypeName = scriptTypeVal switch
                        {
                            1 => "RunAlways",
                            _ => "RunOnce",
                        };
                        if (scriptTypeVal != 0)
                            hasNonDefaultOptions = true;
                    }
                    else if (
                        namedArg.Key == "RunGroupOrder"
                        && namedArg.Value.Value is int orderVal
                    )
                    {
                        runGroupOrder = orderVal;
                        if (orderVal != 0)
                            hasNonDefaultOptions = true;
                    }
                }
            }

            var loc = classDeclaration.Identifier.GetLocation();
            var lineSpan = loc.GetLineSpan();

            return new ScriptInfo(
                symbol.ToDisplayString(),
                hasParameterlessCtor,
                lineSpan.Path,
                lineSpan.StartLinePosition.Line,
                lineSpan.StartLinePosition.Character,
                scriptTypeName,
                runGroupOrder,
                hasNonDefaultOptions
            );
        }

        private static string SanitizeNamespace(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return "DbUp.Generated";

            // Split by dots to preserve the namespace hierarchy, then sanitize each segment
            var parts = name.Split('.');
            var sanitizedParts = parts.Select(SanitizeIdentifier);
            return string.Join(".", sanitizedParts);
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return "_";

            var sb = new StringBuilder(name.Length + 1);
            if (char.IsDigit(name[0]))
            {
                sb.Append('_');
            }

            foreach (var c in name)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.ToString();
        }

        private record ScriptInfo(
            string FullyQualifiedName,
            bool HasParameterlessConstructor,
            string FilePath,
            int StartLine,
            int StartChar,
            string ScriptTypeName,
            int RunGroupOrder,
            bool HasNonDefaultOptions
        );
    }
}

namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}
